name: appointment_app
description: "A new Flutter project."

# This line prevents accidental publishing to pub.dev for private packages.
publish_to: 'none'

# Version and build number for the app.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  # Basic icons package for Cupertino widgets (iOS style).
  cupertino_icons: ^1.0.8

  # Dio: A powerful HTTP client library in Dart for making API requests.
  dio: ^5.7.0

  # easy_localization: Package for handling multiple languages and localization.
  easy_localization: ^3.0.7

  # Core Flutter SDK.
  flutter:
    sdk: flutter

  # flutter_bloc: Used for managing application state using the BLoC pattern.
  flutter_bloc: ^8.1.6

  # flutter_native_splash: Package to create a native splash screen for the app.
  flutter_native_splash: ^2.4.2

  # freezed: A code generator for creating immutable classes with copyWith, equality, and other helpers.
  freezed: ^2.5.7
  
  # get_it: Dependency injection package for Flutter to manage objects and dependencies.
  get_it: ^8.0.1

  # intl: For date and number formatting, locale management.
  intl: ^0.19.0

  # json_annotation: Allows marking Dart classes for JSON serialization and deserialization.
  json_annotation: ^4.9.0
  
  # json_serializable: Code generation for JSON serialization and deserialization.
  json_serializable: ^6.8.0
  
  # pretty_dio_logger: Logs Dio requests, responses, and errors for easier debugging.
  pretty_dio_logger: ^1.4.0
  
  # retrofit: A library for creating HTTP requests based on defined interfaces.
  retrofit: ^4.4.1

dev_dependencies:
  # flutter_lints: Provides best practices and linting for Flutter projects.
  flutter_lints: ^4.0.0

  # flutter_test: Enables writing and running tests within Flutter.
  flutter_test:
    sdk: flutter

  # freezed_annotation: Required for annotations used with freezed to define data models.
  freezed_annotation: ^2.4.4

  # retrofit_generator: Code generator for Retrofit. Must be run with build_runner.
  retrofit_generator: ^9.1.4

  # build_runner: Necessary for running code generation for freezed and retrofit.
  build_runner: ^2.3.3

flutter:
  # This line includes Material Icons font, allowing the use of icons from the Material library.
  uses-material-design: true
  
  # Uncomment and add paths to images to include custom assets for the app.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  
  # Fonts can be added here to customize the app’s typography.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
