name: appointment_app
description: "A new Flutter project."

# This line prevents accidental publishing to pub.dev for private packages.
publish_to: 'none'

# Version and build number for the app.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  # Cupertino icons for iOS-styled designs
  cupertino_icons: ^1.0.8
  
  # dio: A powerful HTTP client library for making API requests
  dio: ^5.7.0
  
  # easy_localization: Simplifies localization and multi-language support
  easy_localization: ^3.0.7
  
  # flutter: Core Flutter library for building Flutter applications
  flutter:
    sdk: flutter
  
  # flutter_bloc: For state management using Bloc, ideal for complex projects
  flutter_bloc: ^8.1.6
  
  # flutter_native_splash: To create a native splash screen for the app
  flutter_native_splash: ^2.4.2
  
  # flutter_screenutil: Helps adapt UI layouts to different screen sizes
  flutter_screenutil: ^5.9.3
  
  # flutter_svg: Supports displaying SVG files in Flutter
  flutter_svg: ^2.0.10+1
  
  # freezed: Generates immutable classes and simplifies class generation in Flutter
  freezed: ^2.5.7
  
  # get_it: Dependency injection for managing dependencies, suitable for large apps
  get_it: ^8.0.1
  
  # intl: Provides text, number, and date formatting based on locale settings
  intl: ^0.19.0
  
  # json_annotation: Prepares JSON serialization and deserialization code, used with json_serializable
  json_annotation: ^4.9.0
  
  # json_serializable: Automatically generates JSON serialization and deserialization code
  json_serializable: ^6.8.0
  
  # pretty_dio_logger: Logs and formats Dio requests during development for easy debugging
  pretty_dio_logger: ^1.4.0
  
  # retrofit: Simplifies REST API configuration, built on top of dio
  retrofit: ^4.4.1


dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0

  # flutter_test: Enables writing and running tests within Flutter.
  flutter_test:
    sdk: flutter

  # freezed_annotation: Required for annotations used with freezed to define data models.
  freezed_annotation: ^2.4.4

  # retrofit_generator: Code generator for Retrofit. Must be run with build_runner.
  retrofit_generator: ^9.1.4

flutter:
  # This line includes Material Icons font, allowing the use of icons from the Material library.
  uses-material-design: true
  # Uncomment and add paths to images to include custom assets for the app.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # Fonts can be added here to customize the app’s typography.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
