name: appointment_app
description: "A new Flutter project."

# This line prevents accidental publishing to pub.dev for private packages.
publish_to: 'none'

# Version and build number for the app.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.7
  get_it: ^8.0.1
  go_router: ^14.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0

  # flutter_test: Enables writing and running tests within Flutter.
  flutter_test:
    sdk: flutter

  # freezed_annotation: Required for annotations used with freezed to define data models.
  freezed_annotation: ^2.4.4

  # retrofit_generator: Code generator for Retrofit. Must be run with build_runner.
  retrofit_generator: ^9.1.4

flutter:
  # This line includes Material Icons font, allowing the use of icons from the Material library.
  uses-material-design: true
  # Uncomment and add paths to images to include custom assets for the app.
  assets:
    - assets/images/
    - assets/svgs/
  # Fonts can be added here to customize the app’s typography.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
